/**
* this is an example XxxDAO.java
*/
package test.dao;

import java.util.Date;

public class Population {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.preyear
     *
     * @mbggenerated
     */
    private String preyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.preLaborPopulation
     *
     * @mbggenerated
     */
    private String prelaborpopulation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.preEmployedPopulation
     *
     * @mbggenerated
     */
    private String preemployedpopulation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.preFirstPopulation
     *
     * @mbggenerated
     */
    private String prefirstpopulation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.preSecondPopulation
     *
     * @mbggenerated
     */
    private String presecondpopulation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.preThirdPopulation
     *
     * @mbggenerated
     */
    private String prethirdpopulation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.preInsurance
     *
     * @mbggenerated
     */
    private String preinsurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.preOldRate
     *
     * @mbggenerated
     */
    private String preoldrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column population_employ_insurance_pre_data.preLaborRate
     *
     * @mbggenerated
     */
    private String prelaborrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.id
     *
     * @return the value of population_employ_insurance_pre_data.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.id
     *
     * @param id the value for population_employ_insurance_pre_data.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.create_time
     *
     * @return the value of population_employ_insurance_pre_data.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.create_time
     *
     * @param createTime the value for population_employ_insurance_pre_data.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.modify_time
     *
     * @return the value of population_employ_insurance_pre_data.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.modify_time
     *
     * @param modifyTime the value for population_employ_insurance_pre_data.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.preyear
     *
     * @return the value of population_employ_insurance_pre_data.preyear
     *
     * @mbggenerated
     */
    public String getPreyear() {
        return preyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.preyear
     *
     * @param preyear the value for population_employ_insurance_pre_data.preyear
     *
     * @mbggenerated
     */
    public void setPreyear(String preyear) {
        this.preyear = preyear == null ? null : preyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.preLaborPopulation
     *
     * @return the value of population_employ_insurance_pre_data.preLaborPopulation
     *
     * @mbggenerated
     */
    public String getPrelaborpopulation() {
        return prelaborpopulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.preLaborPopulation
     *
     * @param prelaborpopulation the value for population_employ_insurance_pre_data.preLaborPopulation
     *
     * @mbggenerated
     */
    public void setPrelaborpopulation(String prelaborpopulation) {
        this.prelaborpopulation = prelaborpopulation == null ? null : prelaborpopulation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.preEmployedPopulation
     *
     * @return the value of population_employ_insurance_pre_data.preEmployedPopulation
     *
     * @mbggenerated
     */
    public String getPreemployedpopulation() {
        return preemployedpopulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.preEmployedPopulation
     *
     * @param preemployedpopulation the value for population_employ_insurance_pre_data.preEmployedPopulation
     *
     * @mbggenerated
     */
    public void setPreemployedpopulation(String preemployedpopulation) {
        this.preemployedpopulation = preemployedpopulation == null ? null : preemployedpopulation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.preFirstPopulation
     *
     * @return the value of population_employ_insurance_pre_data.preFirstPopulation
     *
     * @mbggenerated
     */
    public String getPrefirstpopulation() {
        return prefirstpopulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.preFirstPopulation
     *
     * @param prefirstpopulation the value for population_employ_insurance_pre_data.preFirstPopulation
     *
     * @mbggenerated
     */
    public void setPrefirstpopulation(String prefirstpopulation) {
        this.prefirstpopulation = prefirstpopulation == null ? null : prefirstpopulation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.preSecondPopulation
     *
     * @return the value of population_employ_insurance_pre_data.preSecondPopulation
     *
     * @mbggenerated
     */
    public String getPresecondpopulation() {
        return presecondpopulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.preSecondPopulation
     *
     * @param presecondpopulation the value for population_employ_insurance_pre_data.preSecondPopulation
     *
     * @mbggenerated
     */
    public void setPresecondpopulation(String presecondpopulation) {
        this.presecondpopulation = presecondpopulation == null ? null : presecondpopulation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.preThirdPopulation
     *
     * @return the value of population_employ_insurance_pre_data.preThirdPopulation
     *
     * @mbggenerated
     */
    public String getPrethirdpopulation() {
        return prethirdpopulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.preThirdPopulation
     *
     * @param prethirdpopulation the value for population_employ_insurance_pre_data.preThirdPopulation
     *
     * @mbggenerated
     */
    public void setPrethirdpopulation(String prethirdpopulation) {
        this.prethirdpopulation = prethirdpopulation == null ? null : prethirdpopulation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.preInsurance
     *
     * @return the value of population_employ_insurance_pre_data.preInsurance
     *
     * @mbggenerated
     */
    public String getPreinsurance() {
        return preinsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.preInsurance
     *
     * @param preinsurance the value for population_employ_insurance_pre_data.preInsurance
     *
     * @mbggenerated
     */
    public void setPreinsurance(String preinsurance) {
        this.preinsurance = preinsurance == null ? null : preinsurance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.preOldRate
     *
     * @return the value of population_employ_insurance_pre_data.preOldRate
     *
     * @mbggenerated
     */
    public String getPreoldrate() {
        return preoldrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.preOldRate
     *
     * @param preoldrate the value for population_employ_insurance_pre_data.preOldRate
     *
     * @mbggenerated
     */
    public void setPreoldrate(String preoldrate) {
        this.preoldrate = preoldrate == null ? null : preoldrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column population_employ_insurance_pre_data.preLaborRate
     *
     * @return the value of population_employ_insurance_pre_data.preLaborRate
     *
     * @mbggenerated
     */
    public String getPrelaborrate() {
        return prelaborrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column population_employ_insurance_pre_data.preLaborRate
     *
     * @param prelaborrate the value for population_employ_insurance_pre_data.preLaborRate
     *
     * @mbggenerated
     */
    public void setPrelaborrate(String prelaborrate) {
        this.prelaborrate = prelaborrate == null ? null : prelaborrate.trim();
    }
}