package test.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PopulationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public PopulationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andPreyearIsNull() {
            addCriterion("preyear is null");
            return (Criteria) this;
        }

        public Criteria andPreyearIsNotNull() {
            addCriterion("preyear is not null");
            return (Criteria) this;
        }

        public Criteria andPreyearEqualTo(String value) {
            addCriterion("preyear =", value, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearNotEqualTo(String value) {
            addCriterion("preyear <>", value, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearGreaterThan(String value) {
            addCriterion("preyear >", value, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearGreaterThanOrEqualTo(String value) {
            addCriterion("preyear >=", value, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearLessThan(String value) {
            addCriterion("preyear <", value, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearLessThanOrEqualTo(String value) {
            addCriterion("preyear <=", value, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearLike(String value) {
            addCriterion("preyear like", value, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearNotLike(String value) {
            addCriterion("preyear not like", value, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearIn(List<String> values) {
            addCriterion("preyear in", values, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearNotIn(List<String> values) {
            addCriterion("preyear not in", values, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearBetween(String value1, String value2) {
            addCriterion("preyear between", value1, value2, "preyear");
            return (Criteria) this;
        }

        public Criteria andPreyearNotBetween(String value1, String value2) {
            addCriterion("preyear not between", value1, value2, "preyear");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationIsNull() {
            addCriterion("preLaborPopulation is null");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationIsNotNull() {
            addCriterion("preLaborPopulation is not null");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationEqualTo(String value) {
            addCriterion("preLaborPopulation =", value, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationNotEqualTo(String value) {
            addCriterion("preLaborPopulation <>", value, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationGreaterThan(String value) {
            addCriterion("preLaborPopulation >", value, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationGreaterThanOrEqualTo(String value) {
            addCriterion("preLaborPopulation >=", value, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationLessThan(String value) {
            addCriterion("preLaborPopulation <", value, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationLessThanOrEqualTo(String value) {
            addCriterion("preLaborPopulation <=", value, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationLike(String value) {
            addCriterion("preLaborPopulation like", value, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationNotLike(String value) {
            addCriterion("preLaborPopulation not like", value, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationIn(List<String> values) {
            addCriterion("preLaborPopulation in", values, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationNotIn(List<String> values) {
            addCriterion("preLaborPopulation not in", values, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationBetween(String value1, String value2) {
            addCriterion("preLaborPopulation between", value1, value2, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPrelaborpopulationNotBetween(String value1, String value2) {
            addCriterion("preLaborPopulation not between", value1, value2, "prelaborpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationIsNull() {
            addCriterion("preEmployedPopulation is null");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationIsNotNull() {
            addCriterion("preEmployedPopulation is not null");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationEqualTo(String value) {
            addCriterion("preEmployedPopulation =", value, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationNotEqualTo(String value) {
            addCriterion("preEmployedPopulation <>", value, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationGreaterThan(String value) {
            addCriterion("preEmployedPopulation >", value, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationGreaterThanOrEqualTo(String value) {
            addCriterion("preEmployedPopulation >=", value, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationLessThan(String value) {
            addCriterion("preEmployedPopulation <", value, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationLessThanOrEqualTo(String value) {
            addCriterion("preEmployedPopulation <=", value, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationLike(String value) {
            addCriterion("preEmployedPopulation like", value, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationNotLike(String value) {
            addCriterion("preEmployedPopulation not like", value, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationIn(List<String> values) {
            addCriterion("preEmployedPopulation in", values, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationNotIn(List<String> values) {
            addCriterion("preEmployedPopulation not in", values, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationBetween(String value1, String value2) {
            addCriterion("preEmployedPopulation between", value1, value2, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPreemployedpopulationNotBetween(String value1, String value2) {
            addCriterion("preEmployedPopulation not between", value1, value2, "preemployedpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationIsNull() {
            addCriterion("preFirstPopulation is null");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationIsNotNull() {
            addCriterion("preFirstPopulation is not null");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationEqualTo(String value) {
            addCriterion("preFirstPopulation =", value, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationNotEqualTo(String value) {
            addCriterion("preFirstPopulation <>", value, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationGreaterThan(String value) {
            addCriterion("preFirstPopulation >", value, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationGreaterThanOrEqualTo(String value) {
            addCriterion("preFirstPopulation >=", value, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationLessThan(String value) {
            addCriterion("preFirstPopulation <", value, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationLessThanOrEqualTo(String value) {
            addCriterion("preFirstPopulation <=", value, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationLike(String value) {
            addCriterion("preFirstPopulation like", value, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationNotLike(String value) {
            addCriterion("preFirstPopulation not like", value, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationIn(List<String> values) {
            addCriterion("preFirstPopulation in", values, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationNotIn(List<String> values) {
            addCriterion("preFirstPopulation not in", values, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationBetween(String value1, String value2) {
            addCriterion("preFirstPopulation between", value1, value2, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPrefirstpopulationNotBetween(String value1, String value2) {
            addCriterion("preFirstPopulation not between", value1, value2, "prefirstpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationIsNull() {
            addCriterion("preSecondPopulation is null");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationIsNotNull() {
            addCriterion("preSecondPopulation is not null");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationEqualTo(String value) {
            addCriterion("preSecondPopulation =", value, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationNotEqualTo(String value) {
            addCriterion("preSecondPopulation <>", value, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationGreaterThan(String value) {
            addCriterion("preSecondPopulation >", value, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationGreaterThanOrEqualTo(String value) {
            addCriterion("preSecondPopulation >=", value, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationLessThan(String value) {
            addCriterion("preSecondPopulation <", value, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationLessThanOrEqualTo(String value) {
            addCriterion("preSecondPopulation <=", value, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationLike(String value) {
            addCriterion("preSecondPopulation like", value, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationNotLike(String value) {
            addCriterion("preSecondPopulation not like", value, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationIn(List<String> values) {
            addCriterion("preSecondPopulation in", values, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationNotIn(List<String> values) {
            addCriterion("preSecondPopulation not in", values, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationBetween(String value1, String value2) {
            addCriterion("preSecondPopulation between", value1, value2, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPresecondpopulationNotBetween(String value1, String value2) {
            addCriterion("preSecondPopulation not between", value1, value2, "presecondpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationIsNull() {
            addCriterion("preThirdPopulation is null");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationIsNotNull() {
            addCriterion("preThirdPopulation is not null");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationEqualTo(String value) {
            addCriterion("preThirdPopulation =", value, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationNotEqualTo(String value) {
            addCriterion("preThirdPopulation <>", value, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationGreaterThan(String value) {
            addCriterion("preThirdPopulation >", value, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationGreaterThanOrEqualTo(String value) {
            addCriterion("preThirdPopulation >=", value, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationLessThan(String value) {
            addCriterion("preThirdPopulation <", value, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationLessThanOrEqualTo(String value) {
            addCriterion("preThirdPopulation <=", value, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationLike(String value) {
            addCriterion("preThirdPopulation like", value, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationNotLike(String value) {
            addCriterion("preThirdPopulation not like", value, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationIn(List<String> values) {
            addCriterion("preThirdPopulation in", values, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationNotIn(List<String> values) {
            addCriterion("preThirdPopulation not in", values, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationBetween(String value1, String value2) {
            addCriterion("preThirdPopulation between", value1, value2, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPrethirdpopulationNotBetween(String value1, String value2) {
            addCriterion("preThirdPopulation not between", value1, value2, "prethirdpopulation");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceIsNull() {
            addCriterion("preInsurance is null");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceIsNotNull() {
            addCriterion("preInsurance is not null");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceEqualTo(String value) {
            addCriterion("preInsurance =", value, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceNotEqualTo(String value) {
            addCriterion("preInsurance <>", value, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceGreaterThan(String value) {
            addCriterion("preInsurance >", value, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceGreaterThanOrEqualTo(String value) {
            addCriterion("preInsurance >=", value, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceLessThan(String value) {
            addCriterion("preInsurance <", value, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceLessThanOrEqualTo(String value) {
            addCriterion("preInsurance <=", value, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceLike(String value) {
            addCriterion("preInsurance like", value, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceNotLike(String value) {
            addCriterion("preInsurance not like", value, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceIn(List<String> values) {
            addCriterion("preInsurance in", values, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceNotIn(List<String> values) {
            addCriterion("preInsurance not in", values, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceBetween(String value1, String value2) {
            addCriterion("preInsurance between", value1, value2, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreinsuranceNotBetween(String value1, String value2) {
            addCriterion("preInsurance not between", value1, value2, "preinsurance");
            return (Criteria) this;
        }

        public Criteria andPreoldrateIsNull() {
            addCriterion("preOldRate is null");
            return (Criteria) this;
        }

        public Criteria andPreoldrateIsNotNull() {
            addCriterion("preOldRate is not null");
            return (Criteria) this;
        }

        public Criteria andPreoldrateEqualTo(String value) {
            addCriterion("preOldRate =", value, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateNotEqualTo(String value) {
            addCriterion("preOldRate <>", value, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateGreaterThan(String value) {
            addCriterion("preOldRate >", value, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateGreaterThanOrEqualTo(String value) {
            addCriterion("preOldRate >=", value, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateLessThan(String value) {
            addCriterion("preOldRate <", value, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateLessThanOrEqualTo(String value) {
            addCriterion("preOldRate <=", value, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateLike(String value) {
            addCriterion("preOldRate like", value, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateNotLike(String value) {
            addCriterion("preOldRate not like", value, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateIn(List<String> values) {
            addCriterion("preOldRate in", values, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateNotIn(List<String> values) {
            addCriterion("preOldRate not in", values, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateBetween(String value1, String value2) {
            addCriterion("preOldRate between", value1, value2, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPreoldrateNotBetween(String value1, String value2) {
            addCriterion("preOldRate not between", value1, value2, "preoldrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateIsNull() {
            addCriterion("preLaborRate is null");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateIsNotNull() {
            addCriterion("preLaborRate is not null");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateEqualTo(String value) {
            addCriterion("preLaborRate =", value, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateNotEqualTo(String value) {
            addCriterion("preLaborRate <>", value, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateGreaterThan(String value) {
            addCriterion("preLaborRate >", value, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateGreaterThanOrEqualTo(String value) {
            addCriterion("preLaborRate >=", value, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateLessThan(String value) {
            addCriterion("preLaborRate <", value, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateLessThanOrEqualTo(String value) {
            addCriterion("preLaborRate <=", value, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateLike(String value) {
            addCriterion("preLaborRate like", value, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateNotLike(String value) {
            addCriterion("preLaborRate not like", value, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateIn(List<String> values) {
            addCriterion("preLaborRate in", values, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateNotIn(List<String> values) {
            addCriterion("preLaborRate not in", values, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateBetween(String value1, String value2) {
            addCriterion("preLaborRate between", value1, value2, "prelaborrate");
            return (Criteria) this;
        }

        public Criteria andPrelaborrateNotBetween(String value1, String value2) {
            addCriterion("preLaborRate not between", value1, value2, "prelaborrate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}