/**
* this is an example XxxMapper.java
*/
package test.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.dao.Population;
import test.dao.PopulationExample;

public interface PopulationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    int countByExample(PopulationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    int deleteByExample(PopulationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    int insert(Population record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    int insertSelective(Population record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    List<Population> selectByExample(PopulationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    Population selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Population record, @Param("example") PopulationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Population record, @Param("example") PopulationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Population record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table population_employ_insurance_pre_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Population record);
}